### ISSUE TITLE
How can I access your pre-trained model and image data?

### ISSUE THREAD

**Issue by Indigo6** [sharpstill/AU_R-CNN#7]
I tested your model using following command:
>  python train.py --eval_mode -bs 128 -e 1 --iteration 1

but encountered an error:
> Traceback (most recent call last):
  File "train.py", line 460, in <module>
    main()
  File "train.py", line 267, in main
    observation = evaluator.evaluate()
  File "/home/data3/fanglin/AU_R-CNN/AU_rcnn/extensions/AU_evaluator.py", line 50, in evaluate
    for idx, batch in enumerate(it):
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 70, in __next__
    self._previous_epoch_detail = self.epoch_detail
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/iterators/serial_iterator.py", line 96, in epoch_detail
    return self.epoch + self.current_position / self._epoch_size
ZeroDivisionError: division by zero

All dependencies are installed and all needed files are put in the right place

**Comment by Indigo6** [comment]
I found this comes from no image data...

**Comment by sharpstill** [comment]
@Indigo6 Sorry for letting you wait , I have uploaded parts of my trained models to google drive ,
https://drive.google.com/open?id=1Q8tx98QIQnT1yz1uSrCxszkobs8MSgrY
There remains some files have not been uploaded because the network is not good.

**Comment by Indigo6** [comment]
Now I'm able to train AU_r-cnn on my dataset, but I come to wonder how I can compute my own 'mean_rgb.npy'?
I find there are two datasets in your 'Training Necessary Files' with only one 'mean_rgb.npy', does that mean this file is AU-TASK-Universal?

**Comment by Indigo6** [comment]
And It's a bit hard for me to understand the loss calculation in 'faster_rcnn_train_chain.py', which caused an error when training:

> Exception in main training loop: Cannot take a larger sample than population when 'replace=False'
Traceback (most recent call last):
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 187, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/optimizer.py", line 864, in update
    loss = lossfun(*args, **kwds)
  File "/home/data3/fanglin/AU_R-CNN/AU_rcnn/links/model/faster_rcnn/faster_rcnn_train_chain.py", line 136, in __call__
    choice_rest = np.random.choice(np.arange(len(gt_neg_index_array)), size=rest_pick_count, replace=False)
  File "mtrand.pyx", line 948, in numpy.random.mtrand.RandomState.choice
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 476, in <module>
    main()
  File "train.py", line 465, in main
    trainer.run()
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/trainer.py", line 349, in run
    six.reraise(*exc_info)
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/trainer.py", line 316, in run
    update()
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 175, in update
    self.update_core()
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/training/updaters/standard_updater.py", line 187, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "/usr/share/anaconda3/envs/enc/lib/python3.6/site-packages/chainer/optimizer.py", line 864, in update
    loss = lossfun(*args, **kwds)
  File "/home/data3/fanglin/AU_R-CNN/AU_rcnn/links/model/faster_rcnn/faster_rcnn_train_chain.py", line 136, in __call__
    choice_rest = np.random.choice(np.arange(len(gt_neg_index_array)), size=rest_pick_count, replace=False)
  File "mtrand.pyx", line 948, in numpy.random.mtrand.RandomState.choice
ValueError: Cannot take a larger sample than population when 'replace=False'

**Comment by sharpstill** [comment]
@Indigo6 This mean of pixel is not very critical , you can try use my mean file. This is just a mean value over all images and all pixels.
